services:
  - type: web
    name: phishlens
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_DB_URL
        sync: false
    branches:
      - branch: main
